### PR TITLE
feat: typescript react support

### PR DESCRIPTION
**Pull request by keahie**
This adds support for .ts and .tsx files

### CODE REVIEW

**Comment by marcosvega91** [comment]
Hi @keahie thanks for the support :). I'll give you a feedback next when when I'll back home

**Comment by keahie** [comment]
Hi. Cool thanks. About the user who pushed the code, that is also me. I forgot to switch accounts before I created the pull request. That's why these are two different users

**Comment by marcosvega91** [comment]
Hi @keahie thanks for your time :). I'm merging this branch, welcome to contributors 🥳

**Pull request merged**
